/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.math.BigInteger;
import java.util.*;

import com.github.ki5fpl.tronj.abi.FunctionEncoder;
import com.github.ki5fpl.tronj.abi.datatypes.*;
import com.github.ki5fpl.tronj.abi.datatypes.generated.Bytes10;
import com.github.ki5fpl.tronj.abi.datatypes.generated.Uint256;
import com.github.ki5fpl.tronj.abi.datatypes.generated.Uint32;

public class App {
    public String encodeFunctionCalling() {
        System.out.println("! fcuntion sam(bytes _, bool _, address _, uint[])");
        Function function = new Function("sam",
            Arrays.asList(
                new DynamicBytes("dave".getBytes()),
                new Bool(true),
                new Address("T9yKC9LCoVvmhaFxKcdK9iL18TUWtyFtjh"),
                new DynamicArray<>(
                    new Uint(BigInteger.ONE), new Uint(BigInteger.valueOf(2)), new Uint(BigInteger.valueOf(3)))),
            Collections.emptyList());
        String encodedHex = FunctionEncoder.encode(function);
        return encodedHex;
    }

    public static void main(String[] args) {
        System.out.println(new App().encodeFunctionCalling());
    }
}
